Repository thoth-station/source-management, pull requests merged in 2020-09, with the labels that each got.

#26 Automatic update of dependency ogr from 0.12.1 to 0.14.0
  Pipfile.lock
Labels: approved, bot

#29 Release of version 0.3.1
  CHANGELOG.md
  thoth/sourcemanagement/__init__.py
Labels: approved, bot

#31 Fixed missing imports
  thoth/sourcemanagement/__init__.py
Labels: approved, size/XS

#33 Release of version 0.3.2
  CHANGELOG.md
  thoth/sourcemanagement/__init__.py
Labels: approved, bot, size/XS

#30 Automatic update of dependency ogr from 0.14.0 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/S
