Repository thoth-station/source-management, pull requests merged in 2020-06, with the labels that each got.

#15 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: bot, size/S

#5 Service url
  thoth/sourcemanagement/sourcemanagement.py
Labels: approved, size/S

#22 Release of version 0.3.0
  CHANGELOG.md
  thoth/sourcemanagement/__init__.py
Labels: bot

#23 Exception base class doesnt take kwargs
  thoth/sourcemanagement/exception.py
Labels: approved
