Repository thoth-station/source-management, pull requests merged in 2020-11, with the labels that each got.

#36 Remove init file from namespaced package
  setup.py
  thoth/__init__.py
Labels: approved, size/XS

#38 Automatic update of dependency ogr from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/M

#39 Release of version 0.3.3
  CHANGELOG.md
  thoth/sourcemanagement/__init__.py
Labels: approved, bot, size/XS

#42 Github App Authentication
  .pre-commit-config.yaml
  README.rst
  thoth/sourcemanagement/github_authentication.py
  thoth/sourcemanagement/sourcemanagement.py
Labels: approved, size/L

#43 Automatic update of dependency requests from 2.24.0 to 2.25.0
  Pipfile.lock
Labels: approved, bot, size/S

#45 Add sesheta to .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#47 Release of version 0.4.0
  CHANGELOG.md
  thoth/sourcemanagement/__init__.py
Labels: approved, bot, size/XS

#48 Added a getter method for token and expire time
  thoth/sourcemanagement/sourcemanagement.py
Labels: approved, size/XS

#50 Release of version 0.4.1
  CHANGELOG.md
  thoth/sourcemanagement/__init__.py
Labels: approved, bot, size/XS
