Repository thoth-station/source-management, pull requests merged in 2020-05, with the labels that each got.

#6 Fixed piplock
  .zuul.yaml
  Pipfile.lock
  thoth/__init__.py
  thoth/sourcemanagement/__init__.py
  thoth/sourcemanagement/sourcemanagement.py
Labels: approved, size/L

#7 PR's go to forked repo if its a forked repo
  thoth/sourcemanagement/sourcemanagement.py
Labels: approved, size/XS

#9 Release of version 0.2.8
  thoth/sourcemanagement/__init__.py
Labels: bot, size/XS

#10 Readme fix
  README.md
  README.rst
  setup.py
Labels: approved, size/M

#12 Release of version 0.2.9
  thoth/sourcemanagement/__init__.py
Labels: bot, size/XS

#13 Automatic update of dependency ogr from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/S
